/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
(function(){function B(a,b){var d=a.getAscendant("table"),c=b.getAscendant("table"),k=CKEDITOR.tools.buildTableMap(d),f=a.getAscendant("tr",!0).$.rowIndex,e=b.getAscendant("tr",!0).$.rowIndex,p=[],r={},n,l;d.contains(c)&&(b=b.getAscendant({td:1,th:1}),e=b.getAscendant("tr",!0).$.rowIndex);f>e&&(d=f,f=e,e=d,d=a,a=b,b=d);for(d=0;d<k[f].length;d++)if(a.$===k[f][d]){n=d;break}for(d=0;d<k[e].length;d++)if(b.$===k[e][d]){l=d;break}n>l&&(d=n,n=l,l=d);for(d=f;d<=e;d++)for(f=n;f<=l;f++)c=new CKEDITOR.dom.element(k[d][f]),
c.$&&!c.getCustomData("selected_cell")&&(p.push(c),CKEDITOR.dom.element.setMarker(r,c,"selected_cell",!0));CKEDITOR.dom.element.clearAllMarkers(r);return p}function D(a){a=a.data.$;return CKEDITOR.env.ie&&9>CKEDITOR.env.version?1===a.button:0===a.button}function J(a){return(a=a.editable().findOne(".cke_table-faked-selection"))&&a.getAscendant("table")}function C(a,b){var d=a.editable().find(".cke_table-faked-selection"),c;a.fire("lockSnapshot");a.editable().removeClass("cke_table-faked-selection-editor");
for(c=0;c<d.count();c++)d.getItem(c).removeClass("cke_table-faked-selection");0<d.count()&&d.getItem(0).getAscendant("table").removeClass("cke_table-faked-selection-table");a.fire("unlockSnapshot");b&&(g={active:!1},a.getSelection().isInTable()&&a.getSelection().reset())}function x(a,b){var d=[],c,k;for(k=0;k<b.length;k++)c=a.createRange(),c.setStartBefore(b[k]),c.setEndAfter(b[k]),d.push(c);a.getSelection().selectRanges(d)}function K(a){var b=a.editable().find(".cke_table-faked-selection");1>b.count()||
(b=B(b.getItem(0),b.getItem(b.count()-1)),x(a,b))}function L(a,b,d){var c=t(a.getSelection(!0));b=b.is("table")?null:b;var k;(k=g.active&&!g.first)&&!(k=b)&&(k=a.getSelection().getRanges(),k=1<c.length||k[0]&&!k[0].collapsed?!0:!1);if(k)g.first=b||c[0],g.dirty=b?!1:1!==c.length;else if(g.active&&b&&g.first.getAscendant("table").equals(b.getAscendant("table"))){c=B(g.first,b);if(!g.dirty&&1===c.length)return C(a,"mouseup"===d.name);g.dirty=!0;g.last=b;x(a,c)}}function M(a){var b=(a=a.editor||a.sender.editor)&&
a.getSelection(),d=b&&b.getRanges()||[],c;if(b&&(C(a),b.isInTable()&&b.isFake)){1===d.length&&d[0]._getTableElement()&&d[0]._getTableElement().is("table")&&(c=d[0]._getTableElement());c=t(b,c);a.fire("lockSnapshot");for(b=0;b<c.length;b++)c[b].addClass("cke_table-faked-selection");0<c.length&&(a.editable().addClass("cke_table-faked-selection-editor"),c[0].getAscendant("table").addClass("cke_table-faked-selection-table"));a.fire("unlockSnapshot")}}function y(a){function b(a,b){return a&&b?a.equals(b)||
a.contains(b)||b.contains(a)||a.getCommonAncestor(b).is(r):!1}function d(a){return!a.getAscendant("table",!0)&&a.getDocument().equals(c.document)}var c=a.editor||a.listenerData.editor,k=c.getSelection(1),f=J(c),e=a.data.getTarget(),p=e&&e.getAscendant({td:1,th:1},!0),e=e&&e.getAscendant("table",!0),r={table:1,thead:1,tbody:1,tfoot:1,tr:1,td:1,th:1};(function(a,c,f,e){return"mousedown"===a.name&&(D(a)||!e)||"mouseup"===a.name&&!d(a.data.getTarget())&&!b(f,e)?!0:!1})(a,k,f,e)&&C(c,!0);!g.active&&"mousedown"===
a.name&&D(a)&&e&&(g={active:!0},CKEDITOR.document.on("mouseup",y,null,{editor:c}));(p||e)&&L(c,p||e,a);"mouseup"===a.name&&(D(a)&&(d(a.data.getTarget())||b(f,e))&&K(c),g={active:!1},CKEDITOR.document.removeListener("mouseup",y))}function N(a){var b=a.data.getTarget().getAscendant({td:1,th:1},!0);b&&!b.hasClass("cke_table-faked-selection")&&(a.cancel(),a.data.preventDefault())}function O(a,b){function d(a){a.cancel()}var c=a.getSelection(),k=c.createBookmarks(),f=a.document,e=a.createRange(),p=f.getDocumentElement().$,
r=CKEDITOR.env.ie&&9>CKEDITOR.env.version,n=a.blockless||CKEDITOR.env.ie?"span":"div",l,m,z,q;f.getById("cke_table_copybin")||(l=f.createElement(n),m=f.createElement(n),m.setAttributes({id:"cke_table_copybin","data-cke-temp":"1"}),l.setStyles({position:"absolute",width:"1px",height:"1px",overflow:"hidden"}),l.setStyle("ltr"==a.config.contentsLangDirection?"left":"right","-5000px"),l.setHtml(a.getSelectedHtml(!0)),a.fire("lockSnapshot"),m.append(l),a.editable().append(m),q=a.on("selectionChange",d,
null,null,0),r&&(z=p.scrollTop),e.selectNodeContents(l),e.select(),r&&(p.scrollTop=z),setTimeout(function(){m.remove();c.selectBookmarks(k);q.removeListener();a.fire("unlockSnapshot");b&&(a.extractSelectedHtml(),a.fire("saveSnapshot"))},100))}function G(a){var b=a.editor||a.sender.editor;b.getSelection().isInTable()&&O(b,"cut"===a.name)}function P(a){function b(a){a=a.getRanges()[0];var b=a.endContainer.getAscendant("tr",!0);if(b&&a.collapsed){if(a.checkBoundaryOfElement(b,CKEDITOR.START))return 1;
if(a.checkBoundaryOfElement(b,CKEDITOR.END))return 2}return 0}function d(a){var b=0,c;for(c=0;c<a.length;c++)a[c].length>b&&(b=a[c].length);return b}function c(a){var b=a.getAscendant("table"),c=a.getParent().$.rowIndex,b=CKEDITOR.tools.buildTableMap(b),d;for(d=0;d<b[c].length;d++)if((new CKEDITOR.dom.element(b[c][d])).equals(a))return d}var k=a.editor,f=k.dataProcessor,e=k.getSelection(),p=new CKEDITOR.dom.element("body"),r=0,n=0,l=0,m=0,z={},q,h,g,u,w,v;f||(f=new CKEDITOR.htmlDataProcessor(k));
p.setHtml(f.toHtml(a.data.dataValue),{fixForBody:!1});m=p.findOne("table");if(e.getRanges().length&&(e.isInTable()||(q=b(e)))&&(h=t(e),h.length)){a.stop();a=h[0].getAscendant("table");h=t(e,a);g=h[0];l=g.getParent();u=h[h.length-1];w=u.getParent();if(!q)for(f=0;f<h.length;f++)h[f].setHtml("");if(1<p.getChildCount()||!m)h[0].setHtml(p.getHtml()),k.fire("saveSnapshot");else{if(q){h=l.getChildCount();l=w=new CKEDITOR.dom.element("tr");l["insert"+(1===q?"Before":"After")](g.getParent());for(f=0;f<h;f++)g=
new CKEDITOR.dom.element("td"),g.appendTo(l);g=l.getFirst();u=l.getLast();e.selectElement(l);h=t(e)}q=CKEDITOR.tools.buildTableMap(a,l.$.rowIndex,E(g,!0),w.$.rowIndex,c(u));e=CKEDITOR.tools.buildTableMap(m);l=d(e);m=d(q);if(e.length>q.length)for(r=e.length-q.length,f=0;f<r;f++)H(h);if(l>m)for(n=l-m,f=0;f<n;f++)I(h);g=h[0];l=g.getParent();u=h[h.length-1];w=new CKEDITOR.dom.element(a.$.rows[u.getParent().$.rowIndex+r]);u=w.getChild(u.$.cellIndex+n);r=E(h[0],!0);h=c(u);q=CKEDITOR.tools.buildTableMap(a,
l.$.rowIndex,r,w.$.rowIndex,h);for(f=0;f<e.length;f++)for(n=new CKEDITOR.dom.element(a.$.rows[l.$.rowIndex+f]),h=0;h<e[f].length;h++)if(v=new CKEDITOR.dom.element(e[f][h]),p=q[f]&&q[f][h]?new CKEDITOR.dom.element(q[f][h]):null,v&&!v.getCustomData("processed")){if(p&&p.getParent())v.replace(p);else if(0===h||e[f][h-1])(p=0!==h?new CKEDITOR.dom.element(e[f][h-1]):null)&&n.equals(p.getParent())?v.insertAfter(p):0<r?v.insertAfter(new CKEDITOR.dom.element(n.$.cells[r])):n.append(v,!0);CKEDITOR.dom.element.setMarker(z,
v,"processed",!0)}else v.getCustomData("processed")&&p&&p.remove();CKEDITOR.dom.element.clearAllMarkers(z);x(k,B(new CKEDITOR.dom.element(e[0][0]),v));k.fire("saveSnapshot");setTimeout(function(){k.fire("afterPaste")},0)}}}function F(a,b,d){a.on("beforeCommandExec",function(c){-1!==CKEDITOR.tools.array.indexOf(b,c.data.name)&&(c.data.selectedCells=t(a.getSelection()))});a.on("afterCommandExec",function(c){-1!==CKEDITOR.tools.array.indexOf(b,c.data.name)&&d(a,c.data)})}var g={active:!1},A,t,E,H,I;
CKEDITOR.plugins.tableselection={getCellsBetween:B,keyboardIntegration:function(a){function b(a){a.getEnclosedNode()?a.getEnclosedNode().setText(""):a.deleteContents();CKEDITOR.tools.array.forEach(a._find("td"),function(a){a.appendBogus()})}var d=a.editable();d.attachListener(d,"keydown",function(a){function d(b,f){if(!f.length)return null;var k=a.createRange(),l=CKEDITOR.dom.range.mergeRanges(f);CKEDITOR.tools.array.forEach(l,function(a){a.enlarge(CKEDITOR.ENLARGE_ELEMENT)});var m=l[0].getBoundaryNodes(),
g=m.startNode,m=m.endNode;if(g&&g.is&&g.is(e)){for(var q=g.getAscendant("table",!0),h=g.getPreviousSourceNode(!1,CKEDITOR.NODE_ELEMENT,q),t=!1,u=function(a){return!g.contains(a)&&a.is&&a.is("td","th")};h&&!u(h);)h=h.getPreviousSourceNode(!1,CKEDITOR.NODE_ELEMENT,q);!h&&m&&m.is&&!m.is("table")&&m.getNext()&&(h=m.getNext().findOne("td, th"),t=!0);if(h)k["moveToElementEdit"+(t?"Start":"End")](h);else k.setStartBefore(g.getAscendant("table",!0)),k.collapse(!0);l[0].deleteContents();return[k]}if(g)return k.moveToElementEditablePosition(g),
[k]}var f={37:1,38:1,39:1,40:1,8:1,46:1},e=CKEDITOR.tools.extend({table:1},CKEDITOR.dtd.$tableContent);delete e.td;delete e.th;return function(e){var g=e.data.getKey(),n,l=37===g||38==g,m,t,q;if(f[g]&&(n=a.getSelection())&&n.isInTable()&&n.isFake)if(m=n.getRanges(),t=m[0]._getTableElement(),q=m[m.length-1]._getTableElement(),e.data.preventDefault(),e.cancel(),8<g&&46>g)m[0].moveToElementEditablePosition(l?t:q,!l),n.selectRanges([m[0]]);else{for(e=0;e<m.length;e++)b(m[e]);(e=d(t,m))?m=e:m[0].moveToElementEditablePosition(t);
n.selectRanges(m);a.fire("saveSnapshot")}}}(a),null,null,-1);d.attachListener(d,"keypress",function(c){var d=a.getSelection(),f=c.data.$.charCode||13===c.data.getKey(),e;if(d&&d.isInTable()&&d.isFake&&f&&!(c.data.getKeystroke()&CKEDITOR.CTRL)){c=d.getRanges();f=c[0].getEnclosedNode().getAscendant({td:1,th:1},!0);for(e=0;e<c.length;e++)b(c[e]);c[0].moveToElementEditablePosition(f);d.selectRanges([c[0]])}},null,null,-1)},isSupportedEnvironment:!(CKEDITOR.env.ie&&11>CKEDITOR.env.version)};CKEDITOR.plugins.add("tableselection",
{requires:"clipboard,tabletools",onLoad:function(){A=CKEDITOR.plugins.tabletools;t=A.getSelectedCells;E=A.getCellColIndex;H=A.insertRow;I=A.insertColumn;CKEDITOR.document.appendStyleSheet(this.path+"/styles/tableselection.css")},init:function(a){CKEDITOR.plugins.tableselection.isSupportedEnvironment&&(a.addContentsCss&&a.addContentsCss(this.path+"/styles/tableselection.css"),a.on("contentDom",function(){var b=a.editable(),d=b.isInline()?b:a.document,c={editor:a};b.attachListener(d,"mousedown",y,null,
c);b.attachListener(d,"mousemove",y,null,c);b.attachListener(d,"mouseup",y,null,c);b.attachListener(b,"dragstart",N);b.attachListener(a,"selectionCheck",M);CKEDITOR.plugins.tableselection.keyboardIntegration(a);CKEDITOR.plugins.clipboard&&!CKEDITOR.plugins.clipboard.isCustomCopyCutSupported&&(b.attachListener(b,"cut",G),b.attachListener(b,"copy",G))}),a.on("paste",P),F(a,"rowInsertBefore rowInsertAfter columnInsertBefore columnInsertAfter cellInsertBefore cellInsertAfter".split(" "),function(a,d){x(a,
d.selectedCells)}),F(a,["cellMerge","cellMergeRight","cellMergeDown"],function(a,d){x(a,[d.commandData.cell])}),F(a,["cellDelete"],function(a){C(a,!0)}))}})})();