DELIMITER ;

drop table if exists t_user_right;
drop table if exists t_group_right;
drop table if exists t_image_usage;
drop table if exists t_document_usage;
drop table if exists t_image;
drop table if exists t_document;
drop table if exists t_page;
drop table if exists t_template;
drop table if exists t_user2group;
drop table if exists t_group;
drop table if exists t_user;
drop table if exists t_adminlink;
drop table if exists t_controller;
drop table if exists t_bean;
drop table if exists t_field;
drop table if exists t_language;
drop table if exists t_config;
drop table if exists t_id;